---
- name: "Add Node.js 13"
  become: true
  shell:  |
     # Install Node.js LTS version as our base Node.js version
     curl -fsSl https://deb.nodesource.com/setup_lts.x | sudo -E bash -
     sudo apt install -y nodejs

     # use n versionmanager to use node.js v13.8.0
     sudo npm install --global n
     sudo n 13.8.0

- name: "install PM2 Globally"
  npm:
    name: pm2
    global: yes